http:
  middlewares:
    force-secure:
      headers:
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: "same-origin"

    redirect-to-https:
      redirectRegex:
        regex: "^http://(.*)"
        replacement: "https://$1"
        permanent: false

    omit-prefix-api:
      stripPrefix:
        prefixes:
          - "/api"

    return-404:
      errors:
        status:
          - "404"
        service: noop@internal
        query: "/"

  routers:
    redirect-all:
      rule: HostRegexp(`.*`)
      service: noop@internal
      entrypoints:
        - redirect
      middlewares:
        - redirect-to-https@file
      priority: 1

