http:
  middlewares:
    use-sso:
      forwardAuth:
        address: https://auth.local0.ardikabs.com/
        trustForwardHeader: true
        authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,Set-Cookie

    force-secure:
      headers:
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: "same-origin"

    redirect-to-https:
      redirectRegex:
        regex: "^http://(.*)"
        replacement: "https://$1"
        permanent: false

    omit-prefix-api:
      stripPrefix:
        prefixes:
          - "/api"

  routers:
    redirect-all:
      rule: HostRegexp(`.*`)
      service: noop@internal
      entrypoints:
        - redirect
      middlewares:
        - redirect-to-https@file
      priority: 1

